module.exports = {
  a:"C4",
  b:"D4",
  c:"E4",
  d:"F4",
  e:"G4",
  f:"A4",
  g:"B4",
  h:"C5",
  i:"D5",
  j:"E5",
  k:"F5",
  l:"G5",
  m:"A5",
  n:"B5",
  o:"C4",
  p:"D4",
  r:"E4",
  s:"C4", //F4
  t:"G4",
  u:"A4",
  v:"B5",
  x:"F4",
  y:"D5",
  z:"E5",
  å:"F5",
  ä:"G5",
  ö:"B5"
};
/*
key: 'st', value: 28 },
{ key: 'vi', value: 24 },
{ key: 'fö', value: 22 },
{ key: 'an', value: 16 },
{ key: 'va', value: 16 },
{ key: 'de', value: 16 },
{ key: 'in', value: 15 },
{ key: 'sa', value: 15 },
{ key: 'ma', value: 14 },
{ key: 'lä', value: 13 },
{ key: 'sv', value: 13 },
{ key: 'be', value: 12 },
{ key: 'fr', value: 12 },
{ key: 'mi', value: 12 },
{ key: 'vä', value: 12 },
{ key: 'ti', value: 12 },
{ key: 'se', value: 12 },
*/
